table DimCustomer
	lineageTag: f30b2cf5-aa2c-4fe0-8bfa-a318ac9bb9b8

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 306c1c68-226f-46b4-8241-ea98d5fa10f8
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column contact_email
		dataType: string
		lineageTag: 0479db40-b2b5-447d-954f-5fd129612787
		summarizeBy: none
		sourceColumn: contact_email

		annotation SummarizationSetBy = Automatic

	column contact_name
		dataType: string
		lineageTag: 30ea19e7-8fc9-4dfd-8d61-48347754597a
		summarizeBy: none
		sourceColumn: contact_name

		annotation SummarizationSetBy = Automatic

	column contact_phone
		dataType: string
		lineageTag: bca7ff4a-b48f-40ee-bb79-f30d95c07db4
		summarizeBy: none
		sourceColumn: contact_phone

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tomgo\OneDrive\Documents\vscode-projects\ascent-analytics\powerbi\data_export\DimCustomer.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"contact_email", type text}, {"contact_name", type text}, {"contact_phone", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

