table DimGuide
	lineageTag: e6b67a6b-36a8-409d-97d9-84bda5afbd7a

	measure 'Guide Cumulative Revenue' =
			
			VAR CurrentRank =
			    RANKX ( ALL ( DimGuide ), CALCULATE ( [Revenue] ), , DESC )
			RETURN
			    SUMX (
			        FILTER (
			            ALL ( DimGuide ),
			            RANKX ( ALL ( DimGuide ), CALCULATE ( [Revenue] ), , DESC ) <= CurrentRank
			        ),
			        CALCULATE ( [Revenue] )
			    )
		lineageTag: e989f375-8291-4081-bdc8-afbf940750d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Guide Cumulative %' =
			
			DIVIDE ( [Guide Cumulative Revenue], CALCULATE ( [Revenue], ALL ( DimGuide ) ) )
		formatString: 0%;-0%;0%
		lineageTag: 001120e6-30a5-405f-b893-869ca54a5514

	column guide_id
		dataType: int64
		formatString: 0
		lineageTag: cdf6ab8c-acdd-4ffb-a89f-b9d4259687b2
		summarizeBy: none
		sourceColumn: guide_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: e6821054-acf8-48e1-9837-1ba939ba62d5
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 281d33f3-24ac-422b-9328-359c6853b724
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column full_name
		dataType: string
		lineageTag: 6e5d796b-4a72-41b6-a148-f3f47d218199
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

	column qualifications
		dataType: string
		lineageTag: 7ce37b11-fb97-41ea-945f-4657b9026fa6
		summarizeBy: none
		sourceColumn: qualifications

		annotation SummarizationSetBy = Automatic

	column years_experience
		dataType: int64
		formatString: 0
		lineageTag: 09554b8d-ebe2-4b65-baf4-79d769223ec8
		summarizeBy: none
		sourceColumn: years_experience

		annotation SummarizationSetBy = Automatic

	column languages
		dataType: string
		lineageTag: e61880ee-64d4-407a-bdbb-1637edd91191
		summarizeBy: none
		sourceColumn: languages

		annotation SummarizationSetBy = Automatic

	column employment_type
		dataType: string
		lineageTag: 3d7aa828-45e6-49a4-a958-d70409633627
		summarizeBy: none
		sourceColumn: employment_type

		annotation SummarizationSetBy = Automatic

	column day_rate_gbp
		dataType: double
		lineageTag: c62597b6-4f41-44d8-88a6-159b418069fb
		summarizeBy: none
		sourceColumn: day_rate_gbp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column primary_region_id
		dataType: int64
		formatString: 0
		lineageTag: aebcb394-0dd1-47be-ae5b-94688971fe93
		summarizeBy: none
		sourceColumn: primary_region_id

		annotation SummarizationSetBy = Automatic

	column active
		dataType: int64
		formatString: 0
		lineageTag: a2ea2074-2a69-4f54-aaeb-feb1c35fd4f8
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column discount_tendency_pct
		dataType: double
		lineageTag: 78baf366-aaec-4565-8f94-17d3d87ea097
		summarizeBy: none
		sourceColumn: discount_tendency_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Experience Band' = SWITCH(TRUE(), DimGuide[years_experience] < 5, "Junior (<5 yrs)", DimGuide[years_experience] < 15, "Experienced (5-15 yrs)", "Veteran (15+ yrs)")
		lineageTag: 23c381d1-c049-48be-a2ed-ff1fa29b8348
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DimGuide = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tomgo\OneDrive\Documents\vscode-projects\ascent-analytics\powerbi\data_export\DimGuide.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"guide_id", Int64.Type}, {"first_name", type text}, {"last_name", type text}, {"full_name", type text}, {"qualifications", type text}, {"years_experience", Int64.Type}, {"languages", type text}, {"employment_type", type text}, {"day_rate_gbp", type number}, {"primary_region_id", Int64.Type}, {"active", Int64.Type}, {"discount_tendency_pct", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

