table DimMarketingChannel
	lineageTag: c3d2c051-e22f-49f3-ba6d-cdf83e28fab8

	column channel_id
		dataType: int64
		formatString: 0
		lineageTag: 949bd867-28cc-4640-b256-96a38e59755b
		summarizeBy: none
		sourceColumn: channel_id

		annotation SummarizationSetBy = Automatic

	column channel_name
		dataType: string
		lineageTag: 242364bc-f16b-4c68-8207-2dc6938c460b
		summarizeBy: none
		sourceColumn: channel_name

		annotation SummarizationSetBy = Automatic

	column channel_type
		dataType: string
		lineageTag: ed386b4c-94e2-428d-9e9f-eb4d321a01bc
		summarizeBy: none
		sourceColumn: channel_type

		annotation SummarizationSetBy = Automatic

	partition DimMarketingChannel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tomgo\OneDrive\Documents\vscode-projects\ascent-analytics\powerbi\data_export\DimMarketingChannel.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"channel_id", Int64.Type}, {"channel_name", type text}, {"channel_type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

