table Summary_CustomerLTV
	lineageTag: e4344931-5e5a-4ade-b1d0-3899f43ee6a5

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 73157281-e546-4508-8d9d-9c917862d313
		summarizeBy: sum
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column contact_name
		dataType: string
		lineageTag: 49feaac9-4a1d-4b5c-8d78-4980ba812e32
		summarizeBy: none
		sourceColumn: contact_name

		annotation SummarizationSetBy = Automatic

	column contact_email
		dataType: string
		lineageTag: 0cbdc452-b750-4ca9-8945-6502ecaa4929
		summarizeBy: none
		sourceColumn: contact_email

		annotation SummarizationSetBy = Automatic

	column total_bookings
		dataType: int64
		formatString: 0
		lineageTag: 6be8302c-583b-4ba2-83c9-f64a966008c1
		summarizeBy: sum
		sourceColumn: total_bookings

		annotation SummarizationSetBy = Automatic

	column lifetime_value
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 93aec436-9154-4156-a00d-e95c4efcd842
		summarizeBy: sum
		sourceColumn: lifetime_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column first_booking_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5cb3e6e0-1c08-4cc4-a2ce-7200d6e5d9d8
		summarizeBy: none
		sourceColumn: first_booking_date

		annotation SummarizationSetBy = Automatic

	column last_booking_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9d8582ad-d418-481b-8144-9a23445c397a
		summarizeBy: none
		sourceColumn: last_booking_date

		annotation SummarizationSetBy = Automatic

	column is_repeat_customer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 56cde7c2-6384-48b7-97ae-921fe683e6db
		summarizeBy: none
		sourceColumn: is_repeat_customer

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition Summary_CustomerLTV = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tomgo\OneDrive\Documents\vscode-projects\ascent-analytics\powerbi\data_export\Summary_CustomerLTV.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"contact_name", type text}, {"contact_email", type text}, {"total_bookings", Int64.Type}, {"lifetime_value", type number}, {"first_booking_date", type datetime}, {"last_booking_date", type datetime}, {"is_repeat_customer", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

