table Summary_WeatherFlaggedCancellations
	lineageTag: b8d046bb-f9d2-4ea8-9bf3-1dcc62526a8c

	measure 'Weather-Flagged Cancellation Rate' = AVERAGE(Summary_WeatherFlaggedCancellations[weather_flagged])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: de4f2241-5ae2-47c4-ac41-f5e217c192ae

	column booking_id
		dataType: int64
		formatString: 0
		lineageTag: 479b23c4-0c78-44f8-a6c7-3d9af9c8a49a
		summarizeBy: sum
		sourceColumn: booking_id

		annotation SummarizationSetBy = Automatic

	column route_name
		dataType: string
		lineageTag: 626d91dc-8e29-4aef-82be-41dfea4ae3b1
		summarizeBy: none
		sourceColumn: route_name

		annotation SummarizationSetBy = Automatic

	column region_name
		dataType: string
		lineageTag: 022d8213-4b09-4fc8-8c2f-68d2786a45d8
		summarizeBy: none
		sourceColumn: region_name

		annotation SummarizationSetBy = Automatic

	column tour_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 70a38588-7274-4986-95c9-732c96aa20af
		summarizeBy: none
		sourceColumn: tour_date

		annotation SummarizationSetBy = Automatic

	column storm_warning
		dataType: int64
		formatString: 0
		lineageTag: f7863200-6362-4b7d-9112-34fca574f9e6
		summarizeBy: sum
		sourceColumn: storm_warning

		annotation SummarizationSetBy = Automatic

	column rain_mm
		dataType: double
		lineageTag: 069f4369-701d-4371-af25-f9ce1acf1dd2
		summarizeBy: sum
		sourceColumn: rain_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weather_flagged
		dataType: int64
		formatString: 0
		lineageTag: 3efc0090-0296-4079-a0aa-258ba95c6697
		summarizeBy: sum
		sourceColumn: weather_flagged

		annotation SummarizationSetBy = Automatic

	partition Summary_WeatherFlaggedCancellations = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tomgo\OneDrive\Documents\vscode-projects\ascent-analytics\powerbi\data_export\Summary_WeatherFlaggedCancellations.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"booking_id", Int64.Type}, {"route_name", type text}, {"region_name", type text}, {"tour_date", type datetime}, {"storm_warning", Int64.Type}, {"rain_mm", type number}, {"weather_flagged", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

